# Generated by Django 4.0.4 on 2022-05-10 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nextner', '0002_alter_products_file_attachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('delivery_date', 'title'), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='products',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Nextner.types', verbose_name='Тип товара'),
        ),
    ]
