# Generated by Django 4.0.4 on 2022-05-10 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nextner', '0003_alter_products_options_alter_products_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Nextner.addreses', verbose_name='Адрес пункта выдачи'),
        ),
    ]
